In [1]:
import pandas as pd
import ast
from pathlib import Path

In [2]:
DATA_BASE = Path.cwd().parent / "data"
train_df = pd.read_csv(DATA_BASE / "train.csv")
test_df = pd.read_csv(DATA_BASE / "test.csv")

print("Train:")
display(train_df.head())

print("Test:")
display(test_df.head())

Train:

      id                                              chars
0  37994  ['当', '然', '，', '提', '倡', '『', '讲', '不', '讲', ...
1  40814  ['，', '球', '迷', '在', '一', '家', '酒', '店', '的', ...
2   5148  ['本', '报', '讯', '记', '者', '报', '道', '：', '在', ...
3  21843  ['孩', '子', '的', '读', '书', '费', '用', '现', '在', ...
4   6549  ['战', '争', '爆', '发', '时', '，', '纳', '粹', '的', ...

Test:

      id                                              chars
0  10259  ['据', '此', '间', '新', '闻', '媒', '体', '报', '道', ...
1  10962  ['教', '育', '必', '须', '适', '应', '新', '时', '代', ...
2    884  ['死', '去', '的', '蝴', '蝶', '，', '又', '恍', '恍', ...
3  17894  ['人', '一', '改', '往', '日', '的', '卑', '躬', '态', ...
4  38013  ['针', '对', '此', '案', '圆', '满', '解', '决', '一', ...

In [3]:
print(train_df.columns)
print(test_df.columns)

print("\nExample chars:")
print(test_df.iloc[0]["chars"])

Index(['id', 'chars'], dtype='str')
Index(['id', 'chars'], dtype='str')

Example chars:
['据', '此', '间', '新', '闻', '媒', '体', '报', '道', '，', '此', '次', '视', '察', '的', '主', '要', '目', '的', '是', '了', '解', '位', '于', '冲', '突', '地', '区', '及', '近', '处', '的', '边', '防', '部', '队', '的', '战', '备', '情', '况', '。']

In [4]:
predictions = []

for chars in test_df["chars"]:
    chars = ast.literal_eval(chars)
    
    tags = ["S"] * len(chars)
    
    predictions.append(str(tags))

print(predictions[0])

['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S']

In [5]:
submission = pd.DataFrame({
    "id": test_df["id"],
    "bio_tags": predictions
})

submission.head()

      id                                           bio_tags
0  10259  ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', ...
1  10962  ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', ...
2    884  ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', ...
3  17894  ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', ...
4  38013  ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', ...

In [7]:
submission.to_csv(Path.cwd().parent / "submission.csv", index=False)

print("Saved submission.csv")

Saved submission.csv